### ISSUE TITLE
DualShock 3/4 Support 

### ISSUE THREAD

**Issue by MaxLempira** [pathartl/BleemSync#111]
The ability to use DS3/4, Some buttons are mapped incorrectly

**Comment by safetychief8** [comment]
Can you change them in the Bleemsync game menu?

**Comment by ExSOLDIER1** [comment]
This is not a Bleemsync issue. The PS Classic can detect the DS4 and it will semi work (buttons being wrong like you said) however there is no way to change the inputs. You can try messing with the .cfg file if you know what you are doing, otherwise there is a product (https://www.amazon.com/gp/product/B07L334WXC/ref=as_li_ss_tl?ie=UTF8&psc=1&linkCode=sl1&tag=madlittlepixe-20&linkId=473e7722faa89f05fc5f58ab16606f3a&language=en_US) that should support it once released.

**Comment by MaxLempira** [comment]
Well, not a issue but an enhancement. But as you said, there's no way to change inputs...

**Comment by PattonPlays** [comment]
This will be implemented in future releases.
