### ISSUE TITLE
share memory card between some games.

### ISSUE THREAD

**Issue by appletacos** [pathartl/BleemSync#114]
guess more of a request and not an issue. could there be a way to link the same memory card between multiple games? Maybe something like putting a config option to use memcard from game with X game according to their DB entry.  i know this seems odd but i imagine games like metal gear where if you have other konami games on your memcard adds new options. or even games with shared memory card data like resident evil 2. 

edit: i was looking into something related to this and was wondering if Junction links woukd work?

**Comment by MaxLempira** [comment]
Yeah, that would be cool, Some others like GranTurismo 2 Bonus have some gifts for the game

**Comment by pathartl** [comment]
This basically involves a memory card manager. I personally would love to do this, but it will have to be a bit down the line.

**Comment by alucard73** [comment]
same thing for me for Arc The Lad doing a transfer from 1 to arc the lad 2

**Comment by mlpope** [comment]
ive been able to use the same memory card by just running bleemsync.exe with one game set up like it normally should be with the .ini, .png and etc...then i just add the other games in the sequential folders like usually but do not run the bleemsync.exe...only one games shows up in the gui but u can run that single game that is in the gui and from there run whatever other game by loading cd image from emulator options...it is a crude method, yes, but u will be able to use the same memory card(s)

**Comment by pascl** [comment]
Can we have a db table for that with game_id and game_id_linked as fields ?

During the intercept, a search in the db to find if there is the current game_id somewhere to copy in temp the memcards folder from the game_id_linked folder and not from the current game_id (if doesn't exist in the table, nothing to do)

(maybe as card2 instead of card1, I don't know if the pcsx can manage the second one or not...)

Then, when closing game, do the reverse process to copy memcards folder (or just the card1) in the linked folder.

And only the memcards folder (and not the entire .pcsx folder) to keep savestates and config per game entries.

**Comment by andshrew** [comment]
There's actually support for linking the memory cards of games built into Sony's Stock UI, and it's utilised by some games on the Japanese system. That should be leveraged rather than creating something from scratch. 

In the `GAME` table there is a `LINK_GAME_ID` field. This should be set equal to the `GAME_ID` of the game you want to link with. When this exists the Stock UI will automatically create a symlink to `card1.mcd` of the linked game.

Example `GAME` table in regional.db:

| GAME_ID | GAME_TITLE_STRING | ... | LINK_GAME_ID |
| ----- | ------ | -------- | -------- |
| 5 | Resident Evil 2 - Claire | ... |  |
| 6 | Resident Evil 2 - Leon | ... | 5  |
