### ISSUE TITLE
Controller doesnt work

### ISSUE THREAD

**Issue by nobalhao** [pathartl/BleemSync#151]
games work fine but the controller only the diagonal arrows works
any advice?

**Comment by pathartl** [comment]
Make sure pcsx.cfg exists in System/Defaults

**Comment by safetychief8** [comment]
For me the controller works completely for most games, but for some like the Tomb Raider series, the direction controls work but none of the buttons do.

**Comment by pathartl** [comment]
See above

**Comment by safetychief8** [comment]
The pcsx.cfg does exist in the system folder, just checked. Could it be one of the files in those gamedata folders causing the non responsive buttons? Again, it’s only for certain games that the buttons don’t work, such as the tomb raider games and a few others.

**Comment by FreudienSlip** [comment]
I would redo the folder completely from a fresh unpacked bleemsync, or try different versions of bleemsync.

**Comment by pathartl** [comment]
Remove all pcsx.cfg files from the game folders, make sure the System/Defaults/pcsx.cfg, and boot the system.

**Comment by safetychief8** [comment]
I removed the pcsx.cfg files from all of the GaneData folders but still have the same issue. Turns out that when I use the switch cd image option using the system menu when in a game, then the tomb raider control buttons work, but don’t work when starting game from the original screen after boot up.

**Comment by pathartl** [comment]
That's because it's putting the stock config file in its place.

1. Delete the GameData/pcsx.cfg and .pcsx/pcsx.cfg are deleted out of the games folder
2. Make sure that System/Defaults/pcsx.cfg is there. Maybe replace it with the one from the release ZIP to be sure
3. Boot the system, start a game, test controls
4. Verify that pcsx.cfg exists in the GameData and .pcsx folders

**Comment by safetychief8** [comment]
Thank you for the prompt response, I’ll follow those steps exactly. You mentioned earlier that you’re not dealing with control issues at this time, correct? The 8bitdo wireless controller adapter is being released on Monday, I’ll try it out, hopefully it will be compatible.

Sent from my iPad

On Dec 30, 2018, at 5:01 AM, Pat Hartl <notifications@github.com<mailto:notifications@github.com>> wrote:


That's because it's putting the stock config file in its place.

  1.  Delete the GameData/pcsx.cfg and .pcsx/pcsx.cfg are deleted out of the games folder
  2.  Make sure that System/Defaults/pcsx.cfg is there. Maybe replace it with the one from the release ZIP to be sure
  3.  Boot the system, start a game, test controls
  4.  Verify that pcsx.cfg exists in the GameData and .pcsx folders
