### ISSUE TITLE
BleemSync don't start

### ISSUE THREAD

**Issue by Symmy1998** [pathartl/BleemSync#155]
The Playstation Classic with the USB inserted, arrive at the white startup screen and after then the PS switches off without starting the Hack.. help please!
I attach the photos

![1](https://user-images.githubusercontent.com/46253788/50544015-8c8ed580-0be8-11e9-877b-147e20112663.jpg)
![2](https://user-images.githubusercontent.com/46253788/50544016-8c8ed580-0be8-11e9-980d-e2640c02b63f.jpg)
![3](https://user-images.githubusercontent.com/46253788/50544017-8c8ed580-0be8-11e9-869b-89fea919f3b0.jpg)
![4](https://user-images.githubusercontent.com/46253788/50544018-8c8ed580-0be8-11e9-88e3-749c80bea7f8.jpg)
![5](https://user-images.githubusercontent.com/46253788/50544020-8d276c00-0be8-11e9-8c06-5766d4658112.jpg)

**Comment by 1880rafc1880** [comment]
i had the same problem here now i took out the usb and plugged id back into my computer and opend the file game's and i discovered that in the map gamedata was created an extra file and if i deleted it the ps started normally from the usb drive...

**Comment by sturmf4lke** [comment]
i had the same problem. in my case the problem came from the games, not the hack. i solved it by put in correct 226x226 pixel png for the previews.
but you can easy test:

-download latest version
-extract
-execute bleemsync (without adding games just use the dummys) (use administrator priviliges if you use windows)
-put it on your stick and try to start.

if the hack is loading, you did something wrong with your games. check png cue bin etc....

**Comment by PattonPlays** [comment]
Hey @Symmy1998    if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
