### ISSUE TITLE
Very slow on return to game select screen (Pressing reset)

### ISSUE THREAD

**Issue by aegeus24** [pathartl/BleemSync#158]
Not sure if related to #98 
Whenever I try to return to the game selection screen, there is a very long pause (30+ secs) Then it asks if I would like to overwrite existing save state.

It possible I have something configured incorrectly. But I am wondering if the long time to process the save state on returning to the selection screen is caused by the size of my USB drive. I have notice quite a long startup pause as well, even after removing the system BleemSync folder.

If you need any more details let me know.

**Comment by ShadowHunter69** [comment]
I had this issue with my 32GB USB stick I just presumed it was the stick it's self because it was a cheap one

**Comment by ShadowHunter69** [comment]
Try removing the bleemsync folder from your USB stick it doesn't need to be on there only on your computer if that doesn't work then try searching Arcade man on YouTube he has links for downloads I compared the files from them to mine they is also a boot menu to choose between retro arch and bleemsync but I didn't add the retro arc folder because I needed the space for now , I'm now using a 64gig micro sd card I had from an old phone because I broke my 32gig I just had to purchase a cheap USB adapter that you can put sd cards in, it currently has 80 games on there and a lot of them are multi disc games so could have a lot more, but it boots straight away no waiting on a black screen and games exit straight away oh and you can also save state when pressing select+triangle and going to exit.

**Comment by aegeus24** [comment]
@allenbaietan Unfortunately no fix.
@ShadowHunter69 Trying this somehow led to my bleemsync not even booting anymore.
At this point I figure I will just wait for the 0.5 release and see if that fixes it with the new payload. Closing.
