### ISSUE TITLE
All games stuck on PS logo screen

### ISSUE THREAD

**Issue by FR4NKENST31N** [pathartl/BleemSync#169]
Hi. I've seen a couple similar posts but they don't include the information or specific things I want to say.
I have followed all tutorials to the tee and all games I upload to my USB seem to be recognized because I see the .png for the game and the game info. But whenever I try to start the game, it gets stuck on the ps logo screen and that's it.
Is this a USB memory compatibility issue? I would think that if the USB is not recognized or compatible, I wouldn't be able to see the games.
I have used USB 1.0, 2.0 and 3.0 different brands and none above 32 GB and the results are the same.
I have many roms, all in .rar or .iso format and I'm using power iso to convert them to .cue and .bin, could this be the problem? Is there another better application to convert? 
Or does this all mean that I have to keep on trying with different USB memories?
Thanks.

**Comment by AluFTW** [comment]
Power ISO didnt work for me. Ive switched to winiso and suddenly most of the games work. Cannot get to work Persona 2 and Gran turismo 2 but im guessing its a rom issue.

**Comment by panaphobic** [comment]
I'm having the same issue with certain games. When I load a game that doesn't work, the "Licensed by Sony Computer Entertainment America" wording at the bottom is messed up and on 2 lines instead of 1. Then it just hangs there. I can press SELECT & △ I can get the PCSX menu to come up and can exit out of it from there without any problems. I did convert some games from .iso .rar and a few others. I tried using a couple different converters but they limit you to a maximum size. Ended up finding one without the limits to it and used that. Wonder if that's what is causing the issue.

**Comment by rs2klee** [comment]
when converting the ones i have i had the most problems with multi .bin files eg. Tekken 3 has 1 data and 2 audio. even if i made one .bin file it wouldnt load up. all the games i did that only have 1 .bin data file and .cue all loaded. i had enough with nothing working so just got the pcsxr that the PSC uses and play on the pc with better graphics options and a ScpServer to use a ps3 controller, after all if your like me you play these games because they work then just turn it off after a while. Played Tekken 3 with my son for about 20mins then he`s had enough then goes on his ps4!! you end up tinkering with the settings more so than just playing the games " still need to test them mind you ;)" I ended up taking the thing back to the shop said it was faulty to get a refund at the time it was £89.99uk  2 weeks later it dropped to £49.99.. that was the final straw,  So even now going to wait untill it gets to £19.99 before i even think about buying another one and the BleemSync problems and fixes are sorted.

**Comment by panaphobic** [comment]
The idea is that you have a novelty item. I have the RaspberryPi running Retroarch and can play pretty much everything up to PS1 and N64. I also have the NES Classic, SNES Classic and the Playstation Classic because they are novelty items. I also have them modded and added my own games to them and I do play them. The best emulation system that I've seen for a good price is the Amazon Fire Stick 4k as it's cheap and runs better than a lot of other options out there. You can also run Retroarch on that which gives you a ton more options. They also have a working one for the Playstation Classic,  although it's still in beta so not everything works right on it. Give it a little time and it'll be working great!

**Comment by rs2klee** [comment]
yup needs more time then ill dive right back into it all still very early stages yet with loads more things to add I think when it gets sorted out.

**Comment by GMMan** [comment]
@FR4NKENST31N Has your issue been resolved?

**Comment by FR4NKENST31N** [comment]
@GMMan Thanks for checking, but no. I haven't been able to get more games running. Some get stuck on the black playstation screen with only the words "playstation" displayed (missing the "Sony computer entertainment text) and the others get stuck on the same screen but the  with the "Sony computer entertainment" text displaying but split on different lines

**Comment by GMMan** [comment]
Try deleting your System\Bios folder. It should get recreated and repopulated with the original BIOS files on next boot. Usually when games don't work properly I've noted it was a BIOS problem.

**Comment by KingSinister7** [comment]
It's a problem with the conversion through power ISO. I have the EXACT same issue. Just download the games in .bin and .cue format. Once you convert them from another format, they will not read for some reason.

**Comment by FR4NKENST31N** [comment]
@KingSinister7 thanks. It's driving me crazy. All roms I've found are zipped or .iso so I'm having a hard time getting a different format

**Comment by PattonPlays** [comment]
Hey @FR4NKENST31N  if you would like some support on your issue please join us at the ModMyClassic Discord server. It's much easier to sit and diagnose problems in that environment. http://discord.gg/96DKEdd
