### ISSUE TITLE
Jedi power battles error

### ISSUE THREAD

**Issue by jzodieru118** [pathartl/BleemSync#198]
Can anyone help me get it working it plays for a bit and then errors out

**Comment by haihappenhuhaba** [comment]
Hi, it’s an issue that’s already started. This game is not playable with the psc. Bc it’s not compatible with the emulator.

**Comment by jzodieru118** [comment]
Any way to get around that

**Comment by GMMan** [comment]
Hello @jzodieru118, thank you for filing an issue. Unfortunately, because this issue is about an emulator problem and is not directly related to the operation of BleemSync, we cannot provide support for it on GitHub Issues. Please try the #sony-support channel on [ModMyClassic's Discord](https://discord.gg/8gygsrw).
