### ISSUE TITLE
Does an UI really needed?

### ISSUE THREAD

**Issue by AX3L87** [pathartl/BleemSync#202]
Hi,
Because the new timeline regarding when v1.0 will be released (instead of v0.7), I'd like to ask you if a Windows/Osx/Linux UI is still needed.

I founded a BleemSync port labelled "AutoBleem" that does not have any desktop app. AutoBleem requires to copy games' .bin files into the Games folder ( in a USB thumbs) and nothing else. 
The database will be self-generated while booting up the PSC as well as games folder structure. Even the (all the Pal and Nstc) cover arts are stored in an offline database into the USB thumbs.

So, implement solutions like those can not be useful, for both the users and the developers?

**Comment by pathartl** [comment]
Yes. Based on the number of tickets we receive and the amount of support requests in the Discord, a UI is essential. We can remove a lot of overhead for users by creating an easy to use interface.

**Comment by swingflip** [comment]
I think the other thing to mention is that the latest build of bleemsync 0.7 and up does a lot more than what the original build of bleemsync and autobleem currently does and will ever do. 

It is now a complete solution rather than just adding games in correct format on a USB, updating a db file and dynamically linking them in. 

Also the previous on console methodologies employed by the original tools are inefficient compared to the redesigned payload.
