### ISSUE TITLE
USB portable HDD vs USB Flash

### ISSUE THREAD

**Issue by DunkSB412** [pathartl/BleemSync#204]
is this only capable of running on a USB Flash drive? I just bought a 1TB portable western digital HDD that doesnt need power supply just powered by the USB-3 cable and it will not load or even get detected by the PS Classic console, but a standard USB Flash drive worked flawless for me?

**Comment by mtrivs** [comment]
You can use a portable HDD, but you need to find a way to power the drive beyond what the PSC can provide.   The front USB ports are limited to ~100mA, which is why USB flash drives (with lower power requirements) work without issue.   You are going to need a powered USB hub to give the HDD added power to function.  Assuming your new HDD is a USB 3 and uses a micro B cable, you can get a [micro B Y-cable](http://a.co/d/6TNb9jm) that provides two male USB A plugs (one that is connected to an external power source and the other connected to the PSC).  

The other possibility involves a hardware modification to remove the USB current limit on the front USB ports.

**Comment by PattonPlays** [comment]
A future version of Bleemsync will allow use of the rear port for storage devices such as flash drives and hard drives. Keep an eye on this page!
