### ISSUE TITLE
FEATURE - KERNEL Add OTG support

### ISSUE THREAD

**Issue by swingflip** [pathartl/BleemSync#286]

**Comment by andresjortiz** [comment]
Hello swingflip. Any progress on this feature?

**Comment by swingflip** [comment]
@andresjortiz it's still being worked on and aimed for 1.1

**Comment by andresjortiz** [comment]
Many thks for your hard work. We are all looking forward to have It ;)

**Comment by andresjortiz** [comment]
Hello swingflip, have you got a release date for the 1.1?

**Comment by bmurphr1** [comment]
I imagine it's one of those things that will be added once it's fully stable and works without any issues.  I know it's hard to wait for OTG support because I'm looking forward to it the most as I have a stack of PS Classics and even more micro USB OTG adapters and being able to plug a flash drive behind the PS Classic and keep both front USB ports open would be amazing.  It would also prevent people from having to perform the voltage mod altogether which can be grueling if you don't know how how to solder well or don't have access to a conductive pen.  It'll be added in time.

**Comment by swingflip** [comment]
It's been added and will feature in next release. It's currently being tested.

**Comment by NateWv** [comment]
How about 4 controller use for nba jam t.e. nfl blitz  etc.....on a powered/non powered usb hub..?
