### ISSUE TITLE
How to restore system

### ISSUE THREAD

**Issue by Pierinolartista** [pathartl/BleemSync#30]
Hello,

i tried to unistall and restore system console using gpghax, but after that 7 stock games not working.
I had create 7 folder games before
[filelist (1).log](https://github.com/pathartl/BleemSync/files/2671207/filelist.1.log)

**Comment by GforceMI69** [comment]
I had 2 of my games stop working after trying to use V0.3.0, was trying to add 2 games and all I kept getting was black screens, did a full initialise of the console and reset everything, but something in the stock code is telling the console to look at the usb drive for the game files, I think something bugged out when resetting after black screen lock up.

V0.3.1 loads the custom games just fine now, including save state on exit.

what we really need is an initial setup code that can do a complete system dump from an untouched console in order to use as a system restore to put the console back to stock, first rule of modding is usually make a full backup of the files you're modifying but we do not have that option atm.

**Comment by jesparchaos** [comment]
none of my  stock games seem to work after 0.3.0. I see them but when I select them it, freezes for a second and remains at the game select screen

**Comment by m3ha** [comment]
First 7 stock games won't start after using 0.3.0. US version. Hope there is a fix. FF7 is one of them that won't start!

**Comment by pathartl** [comment]
For 0.3.0, an extra symlink was created on the stock filesystem that shouldn't have stuck around. To fix this, please replace your lolhack.sh with this:

```#!/bin/sh

killall -s KILL sonyapp showLogo ui_menu

for i in `seq 1 100`
do
	rm /gaadata/$i/GameData
done

cd /data/AppData/sony/pcsx
export PCSX_ESC_KEY=2
/usr/sony/bin/ui_menu --power-off-enable &> /media/System/Logs/ui_menu.log
sync
sync
reboot```

Once completed, you should be able to launch the stock games again. I tested this across 25 games. Once you confirm the games can be started again, make sure everything is up to date to the latest version of BleemSync, including the overwritten lolhack.sh.

**Comment by jesparchaos** [comment]
nothing seems to happen when I do this. The system goes black after the sony screen. no messaging afterwards. It just stays as a black screen. Doesnt turn off or anything.
