### ISSUE TITLE
Bleemsyncui.com is timing out..is it still live?

### ISSUE THREAD

**Issue by voodoochild718** [pathartl/BleemSync#304]
Ive have followed every step and I don't know why your website keeps timing out. I am on a Mac and Ive tried Safari and Google Chrome to no available? Should I try Fire Fox or is there something happening with the site?

**Comment by filmcriticbeta** [comment]
It’s not really a website in the traditional sense - it is located on your classic rather than coming in over the internet.  Did you try accessing it via the IP address ( http://169.254.215.100:5000/ )?  Did you remember to install the RDNIS driver ( https://goo.gl/FQYNW5 )?

**Comment by voodoochild718** [comment]
Oh. Well I know I have the program loaded into my classic but I can't get my Mac to show the classic as a Drive. I installed the Rdnis driver to no luck. The usb stick i have is a 128 Sandisk formatted back to Exfat on Mac. could that be it? also is the a place where I czn find a log and send to you?

**Comment by filmcriticbeta** [comment]
Exfat is supported, so that’s probably not the issue. The logs can be accessed by plugging the usb drive directly into your Mac ( should be a log folder under Bleemsync iirc ). 

Btw what version of macOS are you running? By default High Sierra (10.13) or Mojave (10.14) block 3rd party kexts (such as this driver ) by default. You need to authorise it via the privacy pane under system preferences ( https://developer.apple.com/library/archive/technotes/tn2459/_index.html )

If the driver is properly loaded, the classic should appear in the network pane of system preferences as a Samsung phone.

**Comment by runboy93** [comment]
I had also problems with bleemsyncui.com yesterday (haven't tried today), I even did format on USB drive and tried to do everything again, but for some reason after powering up PSC, LED doesn't change to orange anymore, and so not possible to connect bleemsyncui.com anymore (as Bleemsync not detected on USB drive), I can guess my USB drive is either badly corrupted, or my PC won't let enough power for USB drive (I was possible to get it working via USB power brick 2.4A, but this way I can't connect to PC)

**Comment by TheGreenGoblin** [comment]
And keep in mind that a USB drive that large requires a powered USB hub.

**Comment by runboy93** [comment]
> And keep in mind that a USB drive that large requires a powered USB hub.

So far my SanDisk Ultra Fit 3.1 (32GB) been working fine, but yesterday just were weird as told on earlier post.

**Comment by voodoochild718** [comment]
So I got on to the UI for a brief second after messing around in the config page. I was renewing my DHCP lease to try to get the classic to connect to my network. It work but after I refreshed the web page to see if it was a fluke, it now won't come on. How do I get the classic to connect to my network? It says its connected with a self assigned IP address but it won't connect to the internet.
