### ISSUE TITLE
Pendrive from psc after plug to pc need repair

### ISSUE THREAD

**Issue by OldWitch666** [pathartl/BleemSync#348]
Hello. As above. Toshiba 32 GB pendrive formatted as fat32 with BS 0.4.1 and few games on it. Work good on psc, but when I plug it to my pc I see info "scan and fix". Any solution? Pen is 2.0

**Comment by dridder123** [comment]
It happens alot to me to just let the comp fix it

**Comment by OldWitch666** [comment]
Thanks. Fixing won't delete any files on pen?

**Comment by dridder123** [comment]
No files will be fine

**Comment by dridder123** [comment]
No files will be fine

**Comment by TheGreenGoblin** [comment]
It depends on what sectors are corrupted. I would suggest that once you are sure that all of the files are OK, back the entire flashdrive up onto a hard drive. If the flashdrive becomes corrupted (and it WILL), you can easily restore it. Backups are your friends.

**Comment by swingflip** [comment]
This is why we included extended file system support in > 1.0

exFAT and NTFS are much harder to corrupt bas FAT32 is easily corruptable. Any other tools apart from BS 1.0 uses FAT32 and is generally not a good idea as the liklihood of corrupting the drive is high because of the piss poor power management process on the PSC.
