### ISSUE TITLE
Blank Folder Removal in Game Manager?

### ISSUE THREAD

**Issue by ProcessReliability** [pathartl/BleemSync#356]
Two blank folders appear in Game Manager, not assigned to any title. I did this by pressing "Add Game" without adding any files (my mistake). They create empty spaces in the carousel. Is there a way to remove these without messing everything up? See image for what I'm talking about - selecting the blank folders does not provide an option to delete like it does when a game is attached.
![gamemanagerblankfolders](https://user-images.githubusercontent.com/48057588/53493325-bb96bb80-3a60-11e9-8fd0-ab8a70cf0330.png)

**Comment by Reznorio** [comment]
I'm having the exact same issue.

**Comment by GMMan** [comment]
Tasks:
- [ ] Prevent blank name entries from being created
- [ ] Allow removal of invalid entries

**Comment by BL4Z3D247** [comment]
Couldn't you just insert the USB drive into a computer and manually delete the empty folders?

**Comment by GMMan** [comment]
No, because the items that show up are database-backed, not derived from folders.

**Comment by BL4Z3D247** [comment]
@GMMan, ah, gotcha.

**Comment by Reznorio** [comment]
@BL4Z3D247 Can't speak for the OP, but I already tried that and it didn't work.

**Comment by BL4Z3D247** [comment]
@Reznorio, try this:

1. Download pbPSCReAlpha v1.1.
2. Open pbPSCReAlpha and press "Refresh" to bring up your games.
3. Click the "Transformer" tab  and select "Downgrade (0.4.1 compatible folders)".
4. Once done downgrading database, go to the "Games" folder on your USB drive and delete the empty folders.
5. Go back to pbPSCReAlpha and click "Refresh" again.
6. Click on the "Transformer" tab again and select "Upgrade (1.0.0 compatible folders).
7. Insert the USB drive into you PSC or powered USB hub and see if the blanks are gone.

(Not sure if it would work but this is what I'd try.)

**Comment by ProcessReliability** [comment]
I went back and rebuilt the database with a fresh 1.0.1 install, being careful where I clicked. Looks like @GMMan has it on the dev list so I'm closing the issue.

**Comment by infernocloud** [comment]
Here is a verified work-around. Note: You'll need to pop into your browser's inspector and run some Javascript.

1. First, in the BleemSync website UI select the blank folder in the tree view. Right click on it and go to "Inspect" (in Google Chrome). This will open the document inspector at that element in the HTML. You'll have selected an <a> tag inside of an <li> tag. The <a> tag will have an id = "<number>_anchor" such as id="8_anchor" and the parent <li> element will have id="<number" (such as id="8"). This number (8 in my example) is the reference ID for the game in the BleemSync database.

2. Go to your browser's Javascript console and run this command, substituting <number> for the number you found in step 1.
$.getJSON(`/Games/GetById/<number>`, (data) => {data.Name = "Empty folder"; gameManager._editGameForm.show().setViewModel(data); gameManager._editGameForm.find('.cover-preview').attr('src', '');})

All this does is work around the Javascript error that occurs when trying to load a game with no information. I make the name display as "Empty folder" and hide the cover preview so that you are confident that you aren't deleting an existing game.

3. Click Delete Game as normal.

If there isn't already a fix, I'll submit a pull request for the fix.

**Comment by sigismond0** [comment]
Changing line 143 of game-manager.js to this works:

	if (data.ReleaseDate !== null) {
			data.ReleaseDate = data.ReleaseDate.split('T')[0];
	}

**Comment by JJyro22** [comment]
Sigismond0 posted the solution and it's very effective if you have blank game folders in 
bleemsyncui. It enables you to change anything using the bleemsyncui.com game manager.  Thank you sigismond0!

1. Go to your SONY flash drive and search game-manager.js 
2. Change out line 143 to the if statement above and ctrl+S save your changes
3. Safely remove your SONY flash drive 
4. Put your SONY flash drive back into the PS classic (ensuring it's completely powered off, no lights)
5. Power up PS Classic and wait for the orange light to turn green fully. 
6. Go to bleemsyncui.com and click on a blank game folder. You should see your game options to the right such as cover, title, and info. Add in titles and cover. Google for release date of specific games.
