### ISSUE TITLE
No IP on Ubuntu 17.10

### ISSUE THREAD

**Issue by Zibri** [pathartl/BleemSync#400]
on Ubuntu 17.10 I get this:

> [100258.784975] usb 1-11: new high-speed USB device number 21 using xhci_hcd
> [100258.933810] usb 1-11: New USB device found, idVendor=04e8, idProduct=6863, bcdDevice=ff.ff
> [100258.933815] usb 1-11: New USB device strings: Mfr=3, Product=4, SerialNumber=5
> [100258.933819] usb 1-11: Product: classic
>                 
> [100258.933821] usb 1-11: Manufacturer: BleemSync
>                 
> [100258.933824] usb 1-11: SerialNumber: bc02afae693f
>                 
> [100258.942327] rndis_host 1-11:1.0 usb0: register 'rndis_host' at usb-0000:00:14.0-11, RNDIS device, ce:16:16:c4:60:49
> [100258.943104] cdc_acm 1-11:1.2: ttyACM0: USB ACM device
> [100258.960705] rndis_host 1-11:1.0 enp0s20f0u11: renamed from usb0
> [100258.995872] IPv6: ADDRCONF(NETDEV_UP): enp0s20f0u11: link is not ready
> 

and 

> enp0s20f0u11: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
> inet6 fe80::ffb9:7678:d3df:c469 prefixlen 64 scopeid 0x20
> ether 9e:85:48:15:c0:6b txqueuelen 1000 (Ethernet)
> RX packets 8 bytes 536 (536.0 B)
> RX errors 0 dropped 0 overruns 0 frame 0
> TX packets 196 bytes 43393 (43.3 KB)
> TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0
> 

Does not get any IP.

**Comment by HattDroid** [comment]
Hi,

I have the same issue, it doesn't get one automatically.
I found out you either have to select 'Link-Local Only' through your network manager interface, under IPV4 settings of your connection.
Or simply force it by command line with:

`sudo ifconfig enp0sXXXX 169.254.154.241`

For some reason, they also have an issue with the interface brought up on the PS classic since it seems to change at every reboot.
The IP address 169.254.154.241 seems to be the one it gets every time when using Link-Local Only, so I'm using the same through the command line.

Then you can connect as usual with ssh or telnet:

`ssh root@169.254.215.100`

**Comment by Zibri** [comment]
yes, I knew that. I just reported it so they can fix that. It's annoying.

**Comment by Zibri** [comment]
it seems nobody care though

**Comment by HattDroid** [comment]
I can definitely relate to that. I've only been facing this issue since yesterday and I already find it very annoying. :-D

Anyway, here's a small script I made to help with connecting to the PSC:

```
#!/bin/bash

IFACE_FORMAT='enp0s'

# Assuming there's only one device with that name format
INTERFACE=`ls -1 /sys/class/net/ | grep $IFACE_FORMAT`

sudo ifconfig $INTERFACE 169.254.154.241

ssh root@169.254.215.100
```

**Comment by HattDroid** [comment]
https://gist.github.com/HattDroid/df7865c32a622a5d0372038bdbf749a8
