### ISSUE TITLE
2nd Controller over USB Hub

### ISSUE THREAD

**Issue by siuming2004** [pathartl/BleemSync#42]
When BleemSync is used, 2nd usb port is used. Although we can attach the joystick to a powered usb hub together with the BleemSync USB disk, we cannot use the second controller in the game. 

After some digging, I suspect that it's the udev rule file which configure the sym link that causing the PCSX-rearmed not recognizing the 2nd controller in game.

File: /etc/udev/rules.d/20-joysticks.rules
 
KERNEL=="js*",SUBSYSTEMS=="input",ATTRS{phys}=="usb-musbfsh-hdrc.0-1.2/input0",SYMLINK+="input/joystick1"

**Comment by raimuse** [comment]
I have a hub that goes in the back powered with the power cord of the system i hope some day it can be used as usb port but it does not recognize it for now at all

**Comment by mtrivs** [comment]
Check out this post:
https://www.reddit.com/r/PlaystationClassic/comments/a65nxl/a_method_to_use_the_two_controllers_with_usb_hack/

Looks like someone has found a way to modify the udev rules to allow the 2nd controller to be used alongside a hub.  I haven't tested this myself, but it does look promising.

**A method to use the two controllers with USB hack and a hub**
I have found one way to have the USB hack running and both of the original controllers, using a hub.

Create in the root of your USB stick a file named "20-joystick.rules" with UNIX line breaks and the following content:
```
KERNEL=="js0",SUBSYSTEMS=="input",SYMLINK+="input/joystick0"

KERNEL=="js1",SUBSYSTEMS=="input",SYMLINK+="input/joystick1"
```

Add this to your lolhack.sh script:
```
mount -o bind /media/20-joystick.rules /etc/udev/rules.d/20-joystick.rules

udevadm control --reload-rules

udevadm trigger
```

This won't modify your console, since it virtually mounts the file, so it should be safe.

**Comment by raimuse** [comment]
This is Just Great! Thanks it works excellent, now if they use those rules for the joystick would it be possible for the bitdo bluetooth receiver or any receiver to get the dualshock 4. it sounds probable cause i was able to pair it but no joystick movement. now enjoy some multiplayer classics!!

**Comment by pathartl** [comment]
Added in 0.4.0
