### ISSUE TITLE
Gran Turismo 2 change discs

### ISSUE THREAD

**Issue by safetychief8** [pathartl/BleemSync#45]
Gran Turismo 2 had an arcade and a simulation mode disc, both separate, I can't change to start with the simulation disc, it only allows me to use the arcade disc. How do I change it to start with the simulation disc?

**Comment by SimonPlf** [comment]
Same issue here on Syphon Filter 2 with the 0.3.1 version. When the game asks me to change disc, the PCSX menu shows up to let me choose which file to use (.bin or .cue + the same one with a "_" before). It works but the game won't run and shows a "Disc error". I tried with all the 6 files. Same issue by using the Select + Triangle method then "Change CD image".

To bypass it, the only way I found was pressing Select+Triangle, then "PCSX Menu", next "Load CD image" and selecting the second disc. However, it results in a full boot-up of the game, like you're running your console again, instead of just resuming the game.

Playing with the PAL FR version, FYI.

**Comment by DShiznit** [comment]
Though this is closed, I want to mention for anyone interested that you can use select+triangle at the playstation logo when the game starts to switch discs. This is neccesary for Gran Turismo because the two modes share memory card data, which the PSC isolates per game.
