### ISSUE TITLE
Shuts Down When Exiting Game

### ISSUE THREAD

**Issue by safetychief8** [pathartl/BleemSync#59]
The PS automatically shuts down when exiting a game. Probably something to be corrected in a future update.

**Comment by pathartl** [comment]
Please retry with 0.4.0.

**Comment by safetychief8** [comment]
Still shuts down when exiting, but I now use the in game menu to change discs. Had a game, Star Wars Jedi Battles,  it was crashing the system in the middle of the game and when I rebooted, the system would boot to a black screen after showing the Sony Interactive Entertainment logo. I'll have to reinstall Bleemsync again.

**Comment by blacksunfox** [comment]
SOLVED BY ME !!! 
1. go to games folder and in "search" write ".pcsx".
2. If you have for example 60 games you will see 60 folders and 60 config file with the ".pcsx" word inside (they are config file and folder in every single game)...in this example you will delete 60 files + 60 folders (120 total).
3. Take the "virgin" .pcsx file from the folder games/ 1 / gamedata / ...directly from the .zip file of bleemsync 0.4.1 And copy it.
4. Paste it insiede every gamedata folder of every game (60 paste in this example)
5. Delete all the folder but not the games folder from you usb "SONY"
6.  Open the bleemsync 0.4.1 zip file and copy all the folder in your usb SONY but dont copy the games folder
7. Use bleemsync to sync
8. Enjoy your mod that dont crash again when you reset.
 
The issue is something that happen using psxtool or other tools for sort it a/z because whem the tools do it create some issue in config files.

**Comment by PattonPlays** [comment]
This is an issue with the emulator, not bleemsync.
