### ISSUE TITLE
Save States

### ISSUE THREAD

**Issue by ValionPride** [pathartl/BleemSync#78]
Hello,

I have tried version 3.2 and 4.0 and I have the same issue on both.  When I had about 25 games on a thumb drive save states work fine.  Now I have bumped up to 53 titles, and when I hit reset the system fails to create a save state and shuts down.  Is there a limit of how many saves state slots the system can produce?

V/r
Wes

**Comment by ValionPride** [comment]
Just an update to my above issue. 
I was still having issues so I upgraded to 4.1, but still had issues with games saves.  So I started with scaling back to 30 games and then I took all my thumb nails for the games and re-sized them all to be no larger then 266 pixels (at an average of 100k per image).  Doing this reduced the amount of total image size by about 75% (53 games icons are not approximately taking up 5mb of space).  I then started to incrementally add games back on at 5 games per test.  Doing this I was able to get saves states working again.

**Comment by blacksunfox** [comment]
SOLVED BY ME :)
1. go to games folder and in "search" write ".pcsx".
2. If you have for example 60 games you will see 60 folders and 60 config file with the ".pcsx" word inside (they are config file and folder in every single game)...in this example you will delete 60 files + 60 folders (120 total).
3. Take the "virgin" .pcsx file from the folder games/ 1 / gamedata / ...directly from the .zip file of bleemsync 0.4.1 And copy it.
4. Paste it insiede every gamedata folder of every game (60 paste in this example)
5. Delete all the folder but not the games folder from you usb "SONY"
6.  Open the bleemsync 0.4.1 zip file and copy all the folder in your usb SONY but dont copy the games folder
7. Use bleemsync to sync
8. Enjoy your mod that dont crash again when you reset.
 
The issue is something that happen using psxtool or other tools for sort it a/z because whem the tools do it create some issue in config files.
